#!/bin/sh

network=$1
mac=$2
count=$3
invert_status=$4

cacheupdate=/tmp/ping-mac-addr-arp-table

if [ ! -f "$cacheupdate" ] || [ "$(find "$cacheupdate" -mmin +1400)" ];
then
	echo "nmap scan ${network}..."
    nmap -sP ${network} > $cacheupdate
    # 
    #echo "nmap dummy"  > $cacheupdate
fi
#arp -an | grep -i ${mac} | awk '{print $2}' | sed 's/[()]//g'
ip=`arp -an | grep -i ${mac} | awk '{print $2}' | sed 's/[()]//g'`
#echo "IP: $ip"
if [ -n "$ip" ];
then
	ping -n -q -c $count $ip 2>&1 >/dev/null
	status=$?
else
	status=1
	rm -f $cacheupdate
fi
if [ -n "$invert_status" ];
then
	if [ "$status" = "0" ];
	then
		status=1
	else
		status=0
	fi
fi
echo $status
